var data = 
[
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":1,	"mol":0,	"s": 0},	"","meter","length"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":0,	"mol":0,	"s": 0},	"","kilogram","mass"],
	[{"A":1,	"cd":0,	"K":0,	"kg": 0,	"m":0,	"mol":0,	"s": 0},	"","ampere","electric current"],
	[{"A":0,	"cd":0,	"K":1,	"kg": 0,	"m":0,	"mol":0,	"s": 0},	"","kelvin","thermodynamic temperature"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":0,	"mol":1,	"s": 0},	"","mole","amount of substance"],
	[{"A":0,	"cd":1,	"K":0,	"kg": 0,	"m":0,	"mol":0,	"s": 0},	"","candela","luminous intensity"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":0,	"mol":0,	"s": -1},	"Hz","hertz","frequency"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":1,	"mol":0,	"s": -2},	"N","Newton ","force, weight"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":-1,	"mol":0,	"s": -2},	"Pa","Pascal","pressure, stress"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":2,	"mol":0,	"s": -2},	"J","Joule","energy, work, heat"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":2,	"mol":0,	"s": -3},	"W","watt","power, radiant, flux"],
	[{"A":1,	"cd":0,	"K":0,	"kg": 0,	"m":0,	"mol":0,	"s": 1},	"C","coulomb","electric charge, quantity of electricity"],
	[{"A":-1,	"cd":0,	"K":0,	"kg": 1,	"m":2,	"mol":0,	"s": -3},	"V","volt","voltage, electrical potential difference, electromotive force"],
	[{"A":2,	"cd":0,	"K":0,	"kg": -1,	"m":-2,	"mol":0,	"s": 4},	"F","farad","electrical capacitance"],
	[{"A":-2,	"cd":0,	"K":0,	"kg": 1,	"m":2,	"mol":0,	"s": -3},	"&#937;","ohm","electrical resistance, impedance, reactance"],
	[{"A":2,	"cd":0,	"K":0,	"kg": -1,	"m":-2,	"mol":0,	"s": 3},	"S","siemens","electrical conductance"],
	[{"A":-1,	"cd":0,	"K":0,	"kg": 1,	"m":2,	"mol":0,	"s": -2},	"Wb","weber","magnetic flux"],
	[{"A":-1,	"cd":0,	"K":0,	"kg": 1,	"m":0,	"mol":0,	"s": -2},	"T","tesla","magnetic field strength, magnetic flux density"],
	[{"A":-2,	"cd":0,	"K":0,	"kg": 1,	"m":2,	"mol":0,	"s": -2},	"H","henry","inductance"],
	[{"A":0,	"cd":1,	"K":0,	"kg": 0,	"m":-2,	"mol":0,	"s": 0},	"lx","lux","illuminance"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":2,	"mol":0,	"s": -2},	"Gy","Gray","absorbed dose"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":0,	"mol":1,	"s": -1},	"kat","katal","catalytic activity"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":2,	"mol":0,	"s": 0},	"","","area"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":3,	"mol":0,	"s": 0},	"","","volume"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":1,	"mol":0,	"s": -1},	"","","speed, velocity"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":3,	"mol":0,	"s": -1},	"","","volumetric flow"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":1,	"mol":0,	"s": -2},	"","","acceleration"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":1,	"mol":0,	"s": -3},	"","","jerk, jolt"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":1,	"mol":0,	"s": -4},	"","","snap, jounce"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":1,	"mol":0,	"s": -1},	"N s","","momentum, impulse"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":2,	"mol":0,	"s": -1},	"N m s","","angular momentum"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":1,	"mol":0,	"s": -3},	"N/s","","yank"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":-1,	"mol":0,	"s": 0},	"","","wavenumber"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":-2,	"mol":0,	"s": 0},	"","","area density"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":-3,	"mol":0,	"s": 0},	"","","density, mass density"],
	[{"A":0,	"cd":0,	"K":0,	"kg": -1,	"m":3,	"mol":0,	"s": 0},	"","","specific volume"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":-3,	"mol":1,	"s": 0},	"","","amount of substance concentration"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":3,	"mol":-1,	"s": 0},	"","","molar voume"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":2,	"mol":0,	"s": -1},	"J s","","action"],
	[{"A":0,	"cd":0,	"K":-1,	"kg": 1,	"m":2,	"mol":0,	"s": -2},	"J/K","","heat capacity, entropy"],
	[{"A":0,	"cd":0,	"K":-1,	"kg": 1,	"m":2,	"mol":-1,	"s": -2},	"J/(K mol)","","molar heat capacity, molar entropy"],
	[{"A":0,	"cd":0,	"K":-1,	"kg": 0,	"m":2,	"mol":0,	"s": -2},	"J/(K kg)","","specific heat capacity, specific entropy"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":2,	"mol":-1,	"s": -2},	"J/mol","","molar energy"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":2,	"mol":0,	"s": -2},	"J/kg","","specific energy"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":-1,	"mol":0,	"s": -2},	"J/m^3","","energy density"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":0,	"mol":0,	"s": -2},	"N/m","","surface tension, stiffness"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":0,	"mol":0,	"s": -3},	"W/m^2","","heat flux density, irradiance"],
	[{"A":0,	"cd":0,	"K":-1,	"kg": 1,	"m":1,	"mol":0,	"s": -3},	"W/(m K)","","thermal conductivity"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":2,	"mol":0,	"s": -1},	"","","kinematic viscosity, diffusion coefficient"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 1,	"m":-1,	"mol":0,	"s": -1},	"Pa s","","dynamic viscosity"],
	[{"A":1,	"cd":0,	"K":0,	"kg": 0,	"m":-2,	"mol":0,	"s": 1},	"C/m^2","","electric displacement field, polarization vector"],
	[{"A":1,	"cd":0,	"K":0,	"kg": 0,	"m":-3,	"mol":0,	"s": 1},	"C/m^3","","electric charge density"],
	[{"A":1,	"cd":0,	"K":0,	"kg": 0,	"m":-2,	"mol":0,	"s": 0},	"","","electric current density"],
	[{"A":2,	"cd":0,	"K":0,	"kg": -1,	"m":-3,	"mol":0,	"s": 3},	"S/m","","conductivity"],
	[{"A":2,	"cd":0,	"K":0,	"kg": -1,	"m":0,	"mol":-1,	"s": 3},	"S m^2/mol","","molar conductivity"],
	[{"A":2,	"cd":0,	"K":0,	"kg": -1,	"m":-3,	"mol":0,	"s": 4},	"F/m","","permittivity"],
	[{"A":-2,	"cd":0,	"K":0,	"kg": 1,	"m":1,	"mol":0,	"s": -2},	"H/m","","permeability"],
	[{"A":-1,	"cd":0,	"K":0,	"kg": 1,	"m":1,	"mol":0,	"s": -3},	"V/m","","electric field strength"],
	[{"A":1,	"cd":0,	"K":0,	"kg": 0,	"m":-1,	"mol":0,	"s": 0},	"","","magnetic field strength"],
	[{"A":0,	"cd":1,	"K":0,	"kg": 0,	"m":0,	"mol":0,	"s": 1},	"lm s","","luminous energy"],
	[{"A":0,	"cd":1,	"K":0,	"kg": 0,	"m":-2,	"mol":0,	"s": 1},	"lx s","","luminous exposure"],
	[{"A":1,	"cd":0,	"K":0,	"kg": -1,	"m":0,	"mol":0,	"s": 1},	"C/kg","","exposure"],
	[{"A":0,	"cd":0,	"K":0,	"kg": 0,	"m":2,	"mol":0,	"s": -3},	"Gy/s","","absorbed dose rate"],
	[{"A":-2,	"cd":0,	"K":0,	"kg": 1,	"m":3,	"mol":0,	"s": -3},	"&#937; m","","resistivity"]
]